[project]
authors = ["igi-111"]
entry = "main.sw"
license = "Apache-2.0"
name = "prytain"

[dependencies]
perlin = { git = "https://github.com/IGI-111/perlin.git", branch = "master" }
fixed_point = { git = "https://github.com/IGI-111/fixed_point.git" }
